status = [
  "buildkite/cardano-explorer-webapi",
  "ci/hydra:Cardano:cardano-explorer-webapi:required",
]
timeout_sec = 7200
required_approvals = 1
block_labels = [ "WIP", "DO NOT MERGE" ]
delete_merged_branches = true
