resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/594f587bfab626a405ac532112cc0b942ad3efdb/snapshot.yaml
compiler: ghc-8.6.5

allow-newer: true

packages:
  - cardano-db
  - cardano-db/test
  - cardano-db-sync
  - cardano-db-sync-extended

ghc-options:
  cardano-db:               -Wall -Werror -fwarn-redundant-constraints
  cardano-db-test:          -Wall -Werror -fwarn-redundant-constraints
  cardano-db-sync:          -Wall -Werror -fwarn-redundant-constraints
  cardano-db-sync-extended: -Wall -Werror -fwarn-redundant-constraints

extra-deps:

  - git: https://github.com/input-output-hk/cardano-crypto
    commit: 2547ad1e80aeabca2899951601079408becbc92c

  - binary-0.8.7.0
  - bimap-0.4.0
  - brick-0.47.1
  - config-ini-0.2.4.0
  - containers-0.5.11.0
  - data-clist-0.1.2.3
  - ekg-prometheus-adapter-0.1.0.4
  - esqueleto-3.2.2
  - generic-monoid-0.1.0.0
  - libsystemd-journal-1.4.4
  - network-3.1.1.1
  - snap-core-1.0.4.1
  - snap-server-1.1.1.1
  - persistent-2.10.5.1
  - persistent-postgresql-2.10.1.2
  - persistent-template-2.8.2.3
  - prometheus-2.1.2
  - pvss-0.2.0
  - tasty-hedgehog-1.0.0.2
  - text-zipper-0.10.1
  - time-units-1.0.0
  - word-wrap-0.4.1
  - transformers-except-0.1.1
  - text-ansi-0.1.0
  - Diff-0.4.0
  - katip-0.8.3.0
  - moo-1.2
  - gray-code-0.3.1
  - Unique-0.4.7.6
  - statistics-linreg-0.3
  - socks-0.6.1
  - servant-0.17
  - servant-server-0.17
  - connection-0.3.1
  - http-api-data-0.4.1.1
  - time-compat-1.9.2.2
  - quiet-0.2

  - git: https://github.com/input-output-hk/cardano-node
    commit: c1b0ab82ad237dac2c8c22d4089744046a2a1452
    subdirs:
      - cardano-config

  - git: https://github.com/input-output-hk/cardano-shell
    commit: 601bb4324c258e3c8cbd2d532e5696fd09e2582e
    subdirs:
      - cardano-shell

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 594f587bfab626a405ac532112cc0b942ad3efdb
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 20309d5aa56b0ae5fd982465297a1d87aa5658a1
    subdirs:
      - contra-tracer
      - iohk-monitoring
      - plugins/backend-aggregation
      - plugins/backend-ekg
      - plugins/backend-monitoring
      - plugins/backend-trace-forwarder
      - plugins/scribe-systemd
      - tracer-transformers

  - git: https://github.com/input-output-hk/cardano-base
    commit: 9b82346b78e212fcd3e795faf9dd7f3266ab7297
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class
      - slotting

  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: b687fa55369f480cb134c007e534662bef961cea
    subdirs:
      - semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec
      - shelley/chain-and-ledger/dependencies/non-integer
      - shelley/chain-and-ledger/executable-spec
      - shelley/chain-and-ledger/executable-spec/test

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: d309449e6c303a9f0dcc8dcf172df6f0b3195ed5
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 9d9754c9ddcfff82b27c371a545aa4680d86d996
    subdirs:
      - io-sim
      - io-sim-classes
      - network-mux
      - Win32-network
      - ouroboros-network
      - ouroboros-consensus
      - ouroboros-consensus-byron
      - ouroboros-consensus-shelley
      - ouroboros-consensus-cardano
      - ouroboros-consensus/ouroboros-consensus-mock
      - ouroboros-consensus/ouroboros-consensus-test-infra
      - typed-protocols
      - ouroboros-network-framework
      - ouroboros-network-testing
      - typed-protocols-examples
      - cardano-client

nix:
  pure: true
  packages: [ zlib.dev, zlib.out
            , openssl.dev, openssl.out
            , haskell.compiler.ghc865
            , pkg-config
            , systemd.dev
            , postgresql
            ]

