resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/b9bf62f2bab90539809bee13620fe7d29b35928d/snapshot.yaml
compiler: ghc-8.6.5


packages:
  - cardano-explorer-db
  - cardano-explorer-db/test
  - cardano-explorer-node
  - cardano-explorer

ghc-options:
  cardano-explorer-db:          -Wall -Werror -fwarn-redundant-constraints
  cardano-explorer-node:        -Wall -Werror -fwarn-redundant-constraints

extra-deps:
  - binary-0.8.7.0
  - bimap-0.4.0
  - brick-0.47.1
  - config-ini-0.2.4.0
  - containers-0.5.11.0
  - data-clist-0.1.2.3
  - ekg-prometheus-adapter-0.1.0.4
  - esqueleto-3.0.0
  - generic-monoid-0.1.0.0
  - libsystemd-journal-1.4.4
  - persistent-2.10.0
  - persistent-postgresql-2.10.0
  - persistent-template-2.7.2
  - prometheus-2.1.2
  - pvss-0.2.0
  - tasty-hedgehog-1.0.0.1
  - text-zipper-0.10.1
  - time-units-1.0.0
  - word-wrap-0.4.1
  - transformers-except-0.1.1

  - git: https://github.com/input-output-hk/cardano-shell
    commit: 036ff2b45e27a2b47b56f43bee988fbdd1d1d073
    subdirs:
      - cardano-shell

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: b9bf62f2bab90539809bee13620fe7d29b35928d
    subdirs:
      - .
      - test

  - git: http://github.com/well-typed/canonical-json
    commit: ddfe3593b80b5ceb88842bb7a6f2268df75d2c2f

  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 1ebe57df3a76a8ae4e3b5a31a9b85132f71534fc
    subdirs:
      - contra-tracer
      - iohk-monitoring
      - plugins/backend-aggregation
      - plugins/backend-editor
      - plugins/backend-ekg
      - plugins/backend-monitoring
      - plugins/scribe-systemd

  - git: https://github.com/input-output-hk/cardano-node
    commit: e961e3740dc8abfa48ccbed54ba2d2d3c8893258
    subdirs:
      - cardano-config
      - cardano-node

  - git: https://github.com/input-output-hk/cardano-base
    commit: bb262f466d659d94ed6e5500c2dc101f7c2c6b1e
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: edfbc26b34faae0d1f3e007a3ae21dd9716ca8f3
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 6cbde599eba87edf983c620fd8a9ed4015c9b50a
    subdirs:
      - io-sim-classes
      - network-mux
      - ouroboros-network
      - ouroboros-consensus
      - typed-protocols
      - typed-protocols-cbor
