resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/3b2d07ccf4f4ad2c1d1ddefe49b8c138c54854fd/snapshot.yaml
compiler: ghc-8.6.5


packages:
  - cardano-explorer-db
  - cardano-explorer-db/test
  - cardano-explorer-node
  - cardano-explorer

ghc-options:
  cardano-explorer-db:          -Wall -Werror -fwarn-redundant-constraints
  cardano-explorer-node:        -Wall -Werror -fwarn-redundant-constraints

extra-deps:
  - binary-0.8.7.0
  - bimap-0.4.0
  - brick-0.47.1
  - config-ini-0.2.4.0
  - containers-0.5.11.0
  - data-clist-0.1.2.3
  - ekg-prometheus-adapter-0.1.0.4
  - esqueleto-3.0.0
  - generic-monoid-0.1.0.0
  - libsystemd-journal-1.4.4
  - persistent-2.10.0
  - persistent-postgresql-2.10.0
  - persistent-template-2.7.2
  - prometheus-2.1.2
  - pvss-0.2.0
  - tasty-hedgehog-1.0.0.1
  - text-zipper-0.10.1
  - time-units-1.0.0
  - word-wrap-0.4.1
  - transformers-except-0.1.1

  - git: https://github.com/input-output-hk/cardano-shell
    commit: 812a36b8d6714cf76ca3576bdac903bedd88a72b

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 3b2d07ccf4f4ad2c1d1ddefe49b8c138c54854fd
    subdirs:
      - .
      - test

  - git: http://github.com/well-typed/canonical-json
    commit: ddfe3593b80b5ceb88842bb7a6f2268df75d2c2f

  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 1ebe57df3a76a8ae4e3b5a31a9b85132f71534fc
    subdirs:
      - contra-tracer
      - iohk-monitoring
      - plugins/backend-aggregation
      - plugins/backend-editor
      - plugins/backend-ekg
      - plugins/backend-monitoring
      - plugins/scribe-systemd

  - git: https://github.com/input-output-hk/cardano-node
    commit: eb3654f11ff79956a201e10f4afb985bae143bbd
    subdirs:
      - cardano-config
      - cardano-node

  - git: https://github.com/input-output-hk/cardano-base
    commit: 1c9e91cc8cc1deecdd7696d0f7b0b74b8984aa93
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 344aa563be42f6a2682f5b7ff1e4978e4d75359a
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: e8dc8316b21cf6adff6a926e91caff22e208392c
    subdirs:
      - io-sim-classes
      - network-mux
      - ouroboros-network
      - ouroboros-consensus
      - typed-protocols
      - typed-protocols-cbor
